### ISSUE TITLE
Afficher les destinataires déjà présents quand on ajoute des destinataires

### ISSUE THREAD

**Issue by Antoine-BL** [von3007/PetitesPuces#3]
**À fix par moi ou Vince**

### Description
Quand le modal d'ajout des destinataires est afficher et qu'il existe déjà des destinataires associés, ceux-ci s'affichent dans les listes d'ajout et dans la liste des destinataires.

### Pour reproduire
0. (s'il n'y en a pas déjà) Créer un brouillon avec des et y ajouter des destinataires
1. Aller dans Brouillons, sélectionner le brouillon avec des destinataires.
2. Ajouter des destinataires.
3. Les destinataires s'affichent à gauche et dans la colonnes des destinataires

Introduit par ce commit :(https://github.com/von3007/PetitesPuces/commit/e325d9f8ef7990a9a01f4458816f0b4330778a69)

**Comment by VinConstantin** [comment]
Proposition :
On pourrait ne pas afficher les destinataires déjà selectionnés dans la liste de droite (destinataires).
J'avais fait que si tu ajoute un utilisateure qui est déjà présent dans la listeilne se rajoute pas.

Sinon il y a quand même beaucoup de code a changer

**Comment by Antoine-BL** [comment]
Fix par 5e9267344f5304508ec8e78c58cf253cfc045b5b
