### ISSUE TITLE
[securite] page crash

### ISSUE THREAD

**Issue by Simon686** [von3007/PetitesPuces#5]
Si j'ecris sur le site : http://424q.cgodin.qc.ca/fdasf
![image](https://user-images.githubusercontent.com/44792308/53200056-a51adb00-35ee-11e9-8525-bc978f2fe5e1.png)

ou : http://424q.cgodin.qc.ca/client
![image](https://user-images.githubusercontent.com/44792308/53200095-ba900500-35ee-11e9-9793-a5a00505e9e1.png)

ou : http://424q.cgodin.qc.ca/vendeur

![image](https://user-images.githubusercontent.com/44792308/53200140-d398b600-35ee-11e9-8783-428924cadd28.png)

Voici l'exemple du Ali Expresse
https://best.aliexpress.com/admin
![image](https://user-images.githubusercontent.com/44792308/53200217-ffb43700-35ee-11e9-83dc-c919b4721bb2.png)

ou chez Amazon 

https://www.amazon.fr/admin
![image](https://user-images.githubusercontent.com/44792308/53200240-122e7080-35ef-11e9-899f-bcd64139ef86.png)

**Comment by Antoine-BL** [comment]
~~Ce comportement est normal quand l'application est executée en mode débug car la sécurité est~~ ~~disabled.~~

~~C'est pourquoi il faut **toujours** publier en mode release.~~

En fait, l'erreur était causée par des propriétés dans les contrôleurs client et vendeur qui allaient chercher le no de l'utilisateur courant à l'extérieur d'une action de contrôleur.

J'ai corrigé le bug

**Comment by Antoine-BL** [comment]
Et pour l'erreur 404. ce n'est pas le même problème, il faudrait tout simplement créer une [page d'erreur personnalisée](https://benfoster.io/blog/aspnet-mvc-custom-error-pages).
