### ISSUE TITLE
SuccessInscriptionClient.cshtml manquant!

### ISSUE THREAD

**Issue by Antoine-BL** [von3007/PetitesPuces#6]
Quand j'ai essayé de publier l'application, j'ai eu un message qui m'indiquait que SuccessInscriptionClient.cshtml était manquant.

Est-ce normal, le fichier a-t-il été supprimé de git mais non du projet?

**Comment by VinConstantin** [comment]
c'est pas normal, j'ai surement oublié d'ajouter le fichier au git ce matin quand je suis parti.
Mon erreur
