### ISSUE TITLE
Choix de couleur dans le corps du message ne fonctionne pas

### ISSUE THREAD

**Issue by Simon686** [von3007/PetitesPuces#7]
Si je click dessus, il ne va plus afficher les fonctions de l'éditeur texte

Essayer de modifier la couleur du texte 
![image](https://user-images.githubusercontent.com/44792308/53290064-0668b880-376d-11e9-8c0a-c36c938d77f0.png)

Losrque je recompose un courriel 
![image](https://user-images.githubusercontent.com/44792308/53290070-17b1c500-376d-11e9-996a-65d450e22232.png)

**Comment by VinConstantin** [comment]
je vais regarder ca demain, mais je ne garantie  pas qie je vais le fix considerant que ce n'était pas demandé dans l'énoncé

**Comment by Antoine-BL** [comment]
Peux-tu décrire les étapes pour reproduire l'erreur un peu plus clairement?

Le choix de couleur semble fonctionner normalement pour moi...

**Comment by Simon686** [comment]
humm, je pense laisse, faire, la chance de créer cet erreur est comme 10% , c'est que changer le couleur du texte ,plusieurs fois (genre 10 fois) il va etre comme ca.
